#!/usr/bin/env python3
"""Reads angry-gopher's asset table out of its build.zig.

**THE TABLE IS EXTRACTED, NOT COPIED.** Each page of the application embeds its
front-end artifacts by name -- `@embedFile("chat_js_emoji")` -- and those names
resolve only because a build graph declared them. Our build graph has to declare
the same ones, and hand-copying sixty entries is duplicated state that drifts
the first time somebody adds an asset. So it is read from the source of truth
every time port.sh runs.

    extract_assets.py <their build.zig> <gen/assets.zig>
"""
import pathlib
import re
import sys

ROW = re.compile(r'\.\{\s*\.name\s*=\s*"([^"]+)"\s*,\s*\.path\s*=\s*"([^"]+)"\s*\}')

HEADER = """// GENERATED by port.sh from angry-gopher/zig-server/build.zig -- do not edit.
//
// Each page embeds its front-end artifacts by name, and those names resolve
// only because a build graph declared them. This is that declaration, read from
// the application's own table so that the two cannot drift.

pub const Asset = struct { name: []const u8, path: []const u8 };

pub const assets = [_]Asset{
"""


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip())
        return 2
    source, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    if not source.exists():
        print(f"no build.zig at {source}")
        return 2

    rows = ROW.findall(source.read_text())
    if not rows:
        # Loud rather than silently generating an empty table: an empty one
        # compiles and then every @embedFile fails with a confusing message.
        print(f"no asset rows found in {source}; has its table changed shape?")
        return 1

    body = "".join(f'    .{{ .name = "{n}", .path = "{p}" }},\n' for n, p in rows)
    out.write_text(HEADER + body + "};\n")
    print(f"{len(rows)} assets extracted from the application's own table")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
